FROM python:3.9-slim

# Install the PostgreSQL client
RUN apt-get update && apt-get install -y postgresql-client

# Set the working directory in the container
WORKDIR /app

# Copy the elt_script.py into the container at /app
COPY elt_script.py /app/

# Run elt_script.py when the container launches
CMD ["python", "elt_script.py"]


# FROM python:3.9-slim

# RUN apt-get update && apt-get install -y postgresql-client

# COPY elt_script.py

# CMD ["python", "elt_script.py"]